package cl.bennu.commons.enums;

import cl.bennu.commons.enums.base.BaseEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Getter;

import java.util.Arrays;
import java.util.Map;

@Getter
@JsonFormat(shape = JsonFormat.Shape.OBJECT)
public enum CurrencyEnum implements BaseEnum {

    //@formatter:off
    AFGHANI (1, "AFN", "Afgani", "؋")
    , ALGERIAN_DINAR (2, "DZD", "Dinar argelino", "د.ج")
    , ANDORRA_PESETA (3, "ADP", "Peseta andorrana", "₧")
    , ARGENTINIAN_PESO (4, "ARS", "Peso argentino", "$")
    , ARUBAN_GUILDER (5, "AWG", "Florín de Aruba", "ƒ")
    , AUSTRALIAN_DOLLAR (6, "AUD", "Dólar australiano", "$")
    , AZERBAIJANI_MANAT (7, "AZN", "Manat azerbaiyano", "₼")
    , BAHT (8, "THB", "Baht", "฿")
    , BARBADOS_DOLLAR (9, "BBD", "Dólar de Barbados", "$")
    , BELGIAN_FRANC (10, "BEF", "Franco belga", "F")
    , BERMUDIAN_DOLLAR (11, "BMD", "Dólar bermudeño", "$")
    , BOLIVIANO (12, "BOB", "Boliviano", "Bs.")
    , BRAZILIAN_REAL (13, "BRL", "Real", "R$")
    , BRITISH_POUND (14, "GBP", "Libra esterlina", "£")
    , BULGARIAN_LEV (15, "BGN", "Lev búlgaro", "лв")
    , BURUNDI_FRANC (16, "BIF", "Franco burundés", "FBu")
    , CAMBODIAN_RIEL (17, "KHR", "Riel camboyano", "៛")
    , CANADIAN_DOLLAR (18, "CAD", "Dólar canadiense", "$")
    , CAPE_VERDE_ESCUDO (19, "CVE", "Escudo caboverdiano", "Esc")
    , CAYMAN_ISLANDS_DOLLAR (20, "KYD", "Dólar de las Islas Caimán", "$")
    , CHILEAN_PESO (21, "CLP", "Peso chileno", "$")
    , CHINESE_YUAN (22, "CNY", "Yuan", "¥")
    , COLOMBIAN_PESO (23, "COP", "Peso colombiano", "$")
    , CONGOLESE_FRANC (24, "CDF", "Franco congoleño", "FC")
    , CONVERTIBLE_MARK (25, "BAM", "Marco convertible", "KM")
    , CROATIAN_KUNA (26, "HRK", "Kuna croata", "kn")
    , CUBAN_PESO (27, "CUP", "Peso cubano", "$")
    , CZECH_KORUNA (28, "CZK", "Corona checa", "Kč")
    , DANISH_KRONE (29, "DKK", "Corona danesa", "kr")
    , DJIBOUTIAN_FRANC (30, "DJF", "Franco yibutiano", "FDJ")
    , DOMINICAN_PESO (31, "DOP", "Peso dominicano", "RD$")
    , EGYPTIAN_POUND (32, "EGP", "Libra egipcia", "£")
    , EL_SALVADOR_COLON (33, "SVC", "Colón salvadoreño", "₡")
    , EMIRATI_DIRHAM (34, "AED", "Dirham de los EAU", "د.إ")
    , ENGLISH_POUND (35, "GBP", "Libra esterlina inglesa", "£")
    , ERITREAN_NAKFA (36, "ERN", "Nakfa eritreo", "Nfk")
    , ESTONIAN_KROON (37, "EEK", "Kroon estonio", "kr")
    , ETHIOPIAN_BIRR (38, "ETB", "Birr etíope", "Br")
    , EURO (39, "EUR", "Euro", "€")
    , FIJI_DOLLAR (40, "FJD", "Dólar fiyiano", "$")
    , FINNISH_MARKKA (41, "FIM", "Marka finlandesa", "mk")
    , GAMBIA_DALASI (42, "GMD", "Dalasi", "D")
    , GEORGIAN_LARI (43, "GEL", "Lari georgiano", "₾")
    , GHANAIAN_CEDI (44, "GHS", "Cedi ghanés", "₵")
    , GIBRALTAR_POUND (45, "GIP", "Libra de Gibraltar", "£")
    , GRENADINE_DOLLAR (46, "XCD", "Dólar de Granada", "$")
    , GUATEMALAN_QUETZAL (47, "GTQ", "Quetzal guatemalteco", "Q")
    , GUINEAN_FRANC (48, "GNF", "Franco guineano", "FG")
    , GUYANESE_DOLLAR (49, "GYD", "Dólar guyanés", "$")
    , HAITIAN_GOURDE (50, "HTG", "Gourde haitiano", "G")
    , HONDURAN_LEMPIRA (51, "HNL", "Lempira hondureño", "L")
    , HONG_KONG_DOLLAR (52, "HKD", "Dólar de Hong Kong", "$")
    , HUNGARIAN_FORINT (53, "HUF", "Forinto húngaro", "Ft")
    , ICELANDIC_KRONA (54, "ISK", "Corona islandesa", "kr")
    , INDIAN_RUPEE (55, "INR", "Rupia", "₹")
    , INDONESIAN_RUPIAH (56, "IDR", "Rupia indonesia", "Rp")
    , IRANIAN_RIAL (57, "IRR", "Rial iraní", "ر.س")
    , IRAQI_DINAR (58, "IQD", "Dinar iraquí", "ع.د")
    , ISRAELI_NEW_SHEKEL (59, "ILS", "Nuevo shekel israelí", "₪")
    , JAMICAN_DOLLAR (60, "JMD", "Dólar jamaicano", "$")
    , JAPANESE_YEN (61, "JPY", "Yen", "¥")
    , JORDANIAN_DINAR (62, "JOD", "Dinar jordano", "د.ا")
    , KAZAKHSTANI_TENGE (63, "KZT", "Tenge kazajo", "₸")
    , KENYAN_SHILLING (64, "KES", "Chelín keniata", "Sh")
    , KIRIBATI_DOLLAR (65, "AUD", "Dólar de Kiribati", "$")
    , KOREAN_WON (66, "KRW", "Won", "₩")
    , KOSOVO_EURO (67, "EUR", "Euro de Kosovo", "€")
    , KUWAITI_DINAR (68, "KWD", "Dinar kuwaití", "د.ك")
    , KYRGYZSTANI_SOM (69, "KGS", "Som kirguís", "с")
    , LAOTIAN_KIP (70, "LAK", "Kip laosiano", "₭")
    , LATVIAN_LATS (71, "LVL", "Lats letón", "Ls")
    , LEBANESE_POUND (72, "LBP", "Libra libanesa", "ل.ل")
    , LESOTHO_LOTI (73, "LSL", "Loti lesotense", "L")
    , LIBERIAN_DOLLAR (74, "LRD", "Dólar liberiano", "$")
    , LIBYAN_DINAR (75, "LYD", "Dinar libio", "د.ل")
    , LITHUANIAN_LITAS (76, "LTL", "Litas lituano", "Lt")
    , MACEDONIAN_DENAR (77, "MKD", "Denar macedonio", "ден")
    , MALAGASY_ARIARY (78, "MGA", "Ariary malgache", "Ar")
    , MALAWIAN_KWACHA (79, "MWK", "Kwacha malauí", "MK")
    , MALAYSIAN_RINGGIT (80, "MYR", "Ringgit malasio", "RM")
    , MALDIVIAN_RUFIYAA (81, "MVR", "Rufiyaa maldivo", "MRf")
    , MAURITANIAN_OUGUIYA (82, "MRU", "Ouguiya mauritana", "UM")
    , MAURITIAN_RUPEE (83, "MUR", "Rupia mauriciana", "₨")
    , MEXICAN_PESO (84, "MXN", "Peso mexicano", "$")
    , MOLDOVAN_LEU (85, "MDL", "Leu moldavo", "L")
    , MONACO_FRANC (86, "MCF", "Franco monegasco", "F")
    , MONGOLIAN_TUGRIK (87, "MNT", "Tugrik mongoliano", "₮")
    , MOZAMBICAN_METICAL (88, "MZN", "Metical mozambiqueño", "MT")
    , NAMIBIAN_DOLLAR (89, "NAD", "Dólar namibio", "$")
    , NEPALESE_RUPEE (90, "NPR", "Rupia nepalí", "₨")
    , NEW_ZEALAND_DOLLAR (91, "NZD", "Dólar neozelandés", "$")
    , NICARAGUAN_CORDOBA (92, "NIO", "Córdoba nicaragüense", "C$")
    , NIGERIAN_NAIRA (93, "NGN", "Naira nigeriana", "₦")
    , NORWEGIAN_KRONE (94, "NOK", "Corona noruega", "kr")
    , OMANI_RIAL (95, "OMR", "Rial omaní", "ر.ع.")
    , PAKISTANI_RUPEE (96, "PKR", "Rupia pakistaní", "₨")
    , PANAMANIAN_BALBOA (97, "PAB", "Balboa panameña", "B/")
    , PARAGUAYAN_GUARANI (98, "PYG", "Guaraní paraguayo", "₲")
    , PERUVIAN_NUEVO_SOL (99, "PEN", "Nuevo sol peruano", "S/")
    , PHILIPPINE_PESO (100, "PHP", "Peso filipino", "₱")
    , POLISH_ZLOTY (101, "PLN", "Zloty polaco", "zł")
    , PORTUGUESE_ESCUDO (102, "PTE", "Escudo portugués", "$")
    , QATAR_RIAL (103, "QAR", "Rial catarí", "ر.ق")
    , ROMANIAN_LEU (104, "RON", "Leu rumano", "lei")
    , RUSSIAN_ROUBLE (105, "RUB", "Rublo", "₽")
    , RWANDAN_FRANC (106, "RWF", "Franco ruandés", "Fr")
    , SAMOAN_TALA (107, "WST", "Tala samoano", "T")
    , SAINT_HELENA_POUND (108, "SHP", "Libra de Santa Elena", "£")
    , SAINT_KITTS_AND_NEVIS_DOLLAR (109, "XCD", "Dólar de San Cristóbal y Nieves", "$")
    , SAINT_LUCIA_DOLLAR (110, "XCD", "Dólar de Santa Lucía", "$")
    , SAO_TOME_AND_PRINCIPE_DOBRA (111, "STN", "Dobra de Santo Tomé y Príncipe", "Db")
    , SAUDI_RIAL (112, "SAR", "Rial saudí", "ر.س")
    , SENEGAL_FRANC (113, "XOF", "Franco senegalés", "CFA")
    , SEYCHELLOIS_RUPEE (114, "SCR", "Rupia seychellense", "₨")
    , SIERRA_LEONEAN_LEONE (115, "SLL", "Leone sierraleonés", "Le")
    , SINGAPORE_DOLLAR (116, "SGD", "Dólar de Singapur", "$")
    , SOLOMON_ISLANDS_DOLLAR (117, "SBD", "Dólar de las Islas Salomón", "$")
    , SOMALI_SHILLING (118, "SOS", "Chelín somalí", "Sh")
    , SOUTH_AFRICAN_RAND (119, "ZAR", "Rand sudafricano", "R")
    , SOUTH_KOREAN_WON (120, "KRW", "Won surcoreano", "₩")
    , SPANISH_PESETA (121, "ESP", "Peseta española", "₧")
    , SRI_LANKAN_RUPEE (122, "LKR", "Rupia de Sri Lanka", "රු")
    , SURINAME_DOLLAR (123, "SRD", "Dólar de Surinam", "$")
    , SWEDISH_KRONA (124, "SEK", "Corona sueca", "kr")
    , SWISS_FRANC (125, "CHF", "Franco suizo", "CHF")
    , SYRIAN_POUND (126, "SYP", "Libra siria", "£")
    , TAIWANESE_NEW_DOLLAR (127, "TWD", "Nuevo dólar taiwanés", "NT$")
    , TANZANIAN_SHILLING (128, "TZS", "Chelín tanzano", "Sh")
    , THAI_BAHT (129, "THB", "Baht tailandés", "฿")
    , TOGO_FRANC (130, "XOF", "Franco togolés", "CFA")
    , TONGAN_PAANGA (131, "TOP", "Pa'anga tongano", "T$")
    , TRINIDAD_AND_TOBAGO_DOLLAR (132, "TTD", "Dólar de Trinidad y Tobago", "$")
    , TUNISIAN_DINAR (133, "TND", "Dinar tunecino", "د.ت")
    , TURKISH_LIRA (134, "TRY", "Lira turca", "₺")
    , TURKMENISTANI_MANAT (135, "TMT", "Manat turcomano", "m")
    , UGANDA_SHILLING (136, "UGX", "Chelín ugandés", "Sh")
    , UKRAINE_HRYVNIA (137, "UAH", "Grivna ucraniana", "₴")
    , URUGUAYAN_PESO (138, "UYU", "Peso uruguayo", "$")
    , US_DOLLAR (139, "USD", "Dólar estadounidense", "$")
    , UZBEKISTANI_SOM (140, "UZS", "Som uzbeko", "so'm")
    , VATICAN_LIRA (141, "VAT", "Lira vaticana", "₤")
    , VENEZUELAN_BOLÍVAR (142, "VEF", "Bolívar venezolano", "Bs.S")
    , VIETNAMESE_DONG (143, "VND", "Dong vietnamita", "₫")
    , WEST_AFRICAN_FRANC (144, "XOF", "Franco de África Occidental", "CFA")
    , YEMENI_RIAL (145, "YER", "Rial yemení", "ر.ي")
    , ZAMBIAN_KWACHA (146, "ZMW", "Kwacha zambiano", "K")
    , ZIMBABWE_DOLLAR (147, "ZWL", "Dólar zimbabuense", "$")
    , ALBANIAN_LEK (148, "ALL", "Lek albanés", "L")
    , ANGOLAN_KWANZA (149, "AOA", "Kwanza angoleño", "Kz")
    , ARMENIAN_DRAM (150, "AMD", "Dram armenio", "Դ")
    , BAHAMIAN_DOLLAR (151, "BSD", "Dólar de las Bahamas", "$")
    , BAHRAINI_DINAR (152, "BHD", "Dinar bareiní", "د.ب")
    , BANGLADESHI_TAKA (153, "BDT", "Taka bangladesí", "৳")
    , BELARUSIAN_RUBLE (154, "BYN", "Rublo bielorruso", "Br")
    , BELIZE_DOLLAR (155, "BZD", "Dólar beliceño", "$")
    , BHUTANESE_NGULTRUM (156, "BTN", "Ngultrum de Bután", "Nu")
    , BOTSWANAN_PULA (157, "BWP", "Pula de Botsuana", "P")
    , BRUNEI_DOLLAR (158, "BND", "Dólar de Brunéi", "$")
    , BURKINA_FASO_CFA_FRANC (159, "CFA", "Franco CFA de Burkina Faso", "CFA")
    , CAMEROON_CFA_FRANC (160, "CFA", "Franco CFA de Camerún", "CFA")
    , CHAD_CFA_FRANC (161, "CFA", "Franco CFA de Chad", "CFA")
    , CONGOLESE_CFA_FRANC (162, "CFA", "Franco CFA de la República del Congo", "CFA")
    , COMORIAN_FRANC (163, "COM", "Franco de Comoras", "CFP")
    , COSTA_RICA_COLON (164, "CRC", "Colón costarricense", "₡")
    , CYPRIOT_POUND (165, "CYP", "Libra chipriota", "£")
    , GUINEA_CFA_FRANC (166, "CFA", "Franco CFA de Guinea", "CFA")
    , SWAZI_LILANGENI (167, "SZL", "Lilangeni suazi", "L")
    , MALI_CFA_FRANC (168, "CFA", "Franco CFA de Mali", "CFA")
    , NIGER_CFA_FRANC (169, "CFA", "Franco CFA de Níger", "CFA")
    , SENEGAL_CFA_FRANC (170, "CFA", "Franco CFA de Senegal", "CFA")
    , NORTH_KOREAN_WON (171, "KPW", "Won norcoreano", "₩")
    , TOGO_CFA_FRANC (172, "CFA", "Franco CFA de Togo", "CFA")
    , MOROCCAN_DIRHAM (173, "MAD", "Dirham marroquí", "د.م")
    , MYANMAR_KYAT (174, "MMK", "Kyat birmano", "K")
    , BENIN_CFA_FRANC (175, "CFA", "Franco CFA de Benín", "CFA")
    , PAPUA_NEW_GUINEA_KINA (176, "PGK", "Kina de Papúa Nueva Guinea", "K")
    , SERBIAN_DINAR (179, "RSD", "Dinar serbio", "dinar")
    , NETHERLANDS_ANTILLEAN_GUILDER (180, "ANG", "Florín de las Antillas Neerlandesas", "ƒ")
    , SOUTH_SUDANESE_POUND (181, "SSP", "Libra sursudanesa", "£")
    , SUDANESE_POUND (182, "SDG", "Libra sudanesa", "£")
    , TAJIKISTANI_SOMONI (183, "TJS", "Somoni tayiko", "SM")
    , GUINEA_BISSAU_CFA_FRANC (184, "CFA", "Franco CFA de Guinea-Bisáu", "CFA")
    , VANUATU_VAT (185, "VUV", "Vatu de Vanuatu", "Vt")
    , ZIMBABWEAN_DOLLAR (186, "ZWD", "Dólar zimbabuense", "$")
    ;
    //@formatter:on

    CurrencyEnum(Integer id, String code, String name, String symbol) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.symbol = symbol;
    }

    private final Integer id;
    private final String code;
    private final String name;
    private final String symbol;

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static CurrencyEnum valueOf(Object o) {
        if (o instanceof Integer id) {
            return Arrays.stream(values()).filter(e -> e.getId().equals(id)).findFirst().orElse(null);
        } else if (o instanceof Map map) {
            Integer id = (Integer) map.get("id");
            return Arrays.stream(values()).filter(e -> e.getId().equals(id)).findFirst().orElse(null);
        } else {
            return null;
        }
    }

}
